-- Proposed DB cleanup plan
-- Generated by scripts/audit_repo_db_simplification.mjs
-- Non-destructive first: move candidates to archive schema.
-- Execute in staging first, then production after approval.

begin;
create schema if not exists archive;

alter table if exists public.audit_log set schema archive;
alter table if exists public.dim_funnel set schema archive;
alter table if exists public.dim_kpi set schema archive;
alter table if exists public.dim_week set schema archive;
alter table if exists public.fact_attendance_event set schema archive;
alter table if exists public.fact_kpi_weekly set schema archive;
alter table if exists public.fact_kpi_weekly_overrides set schema archive;
alter table if exists public.fact_kpi_weekly_versions set schema archive;
alter table if exists public.funnel_rules set schema archive;
alter table if exists public.manual_money_event set schema archive;
alter table if exists public.raw_hubspot_call_logs set schema archive;
alter table if exists public.raw_hubspot_meetings set schema archive;
alter table if exists public.raw_hubspot_meetings_v3 set schema archive;
alter table if exists public.raw_social_weekly set schema archive;
alter view if exists public.v_kpi_weekly_final set schema archive;
alter function if exists public.apply_fb_funnel_rules(p_start date, p_end date) set schema archive;
alter function if exists public.ensure_week(p_week_start date) set schema archive;
alter function if exists public.ingest_attendance_from_calls(p_week_start date) set schema archive;
alter function if exists public.ingest_attendance_from_calls(p_week_start date, p_title_ilike text, p_day_key text) set schema archive;
alter function if exists public.recompute_all(p_week_start date) set schema archive;
alter function if exists public.recompute_week(p_week_start date) set schema archive;
alter function if exists public.set_week_start_from_occurred_at() set schema archive;
alter function if exists public.upsert_intro_meetings_hs(p_week_start date) set schema archive;
alter function if exists public.week_start_est(ts timestamp with time zone) set schema archive;

-- Keep archived objects for at least 7 days while monitoring dashboards and sync jobs.
-- After the quarantine window, run explicit drops only if no regressions were observed.

-- drop table if exists archive.audit_log cascade;
-- drop table if exists archive.dim_funnel cascade;
-- drop table if exists archive.dim_kpi cascade;
-- drop table if exists archive.dim_week cascade;
-- drop table if exists archive.fact_attendance_event cascade;
-- drop table if exists archive.fact_kpi_weekly cascade;
-- drop table if exists archive.fact_kpi_weekly_overrides cascade;
-- drop table if exists archive.fact_kpi_weekly_versions cascade;
-- drop table if exists archive.funnel_rules cascade;
-- drop table if exists archive.manual_money_event cascade;
-- drop table if exists archive.raw_hubspot_call_logs cascade;
-- drop table if exists archive.raw_hubspot_meetings cascade;
-- drop table if exists archive.raw_hubspot_meetings_v3 cascade;
-- drop table if exists archive.raw_social_weekly cascade;
-- drop view if exists archive.v_kpi_weekly_final cascade;
-- drop function if exists archive.apply_fb_funnel_rules(p_start date, p_end date) cascade;
-- drop function if exists archive.ensure_week(p_week_start date) cascade;
-- drop function if exists archive.ingest_attendance_from_calls(p_week_start date) cascade;
-- drop function if exists archive.ingest_attendance_from_calls(p_week_start date, p_title_ilike text, p_day_key text) cascade;
-- drop function if exists archive.recompute_all(p_week_start date) cascade;
-- drop function if exists archive.recompute_week(p_week_start date) cascade;
-- drop function if exists archive.set_week_start_from_occurred_at() cascade;
-- drop function if exists archive.upsert_intro_meetings_hs(p_week_start date) cascade;
-- drop function if exists archive.week_start_est(ts timestamp with time zone) cascade;

commit;
