const LEADS_METRICS = [
  {
    metric_id: 'leads_total',
    manager_key: 'leads',
    name: 'Leads generated',
    definition: 'Total HubSpot leads created during the period.',
    unit: 'count',
    positive_direction: 'up',
    target: 120,
    thresholds: { watch: 90, red: 70 },
    driver_metric_ids: ['lead_quality_rate', 'paid_social_share'],
    compute_spec: { context_path: 'leads_count' },
  },
  {
    metric_id: 'ad_spend',
    manager_key: 'leads',
    name: 'Ad spend',
    definition: 'Total ad spend attributed to lead acquisition in period.',
    unit: 'currency',
    positive_direction: 'down',
    target: 15000,
    thresholds: { watch: 18000, red: 22000 },
    driver_metric_ids: ['cost_per_lead', 'cost_per_quality_lead'],
    compute_spec: { context_path: 'ad_spend' },
  },
  {
    metric_id: 'ad_leads',
    manager_key: 'leads',
    name: 'Ad platform leads',
    definition: 'Leads reported by ad platform events for the period.',
    unit: 'count',
    positive_direction: 'up',
    target: 150,
    thresholds: { watch: 110, red: 80 },
    driver_metric_ids: ['cost_per_lead'],
    compute_spec: { context_path: 'ad_leads' },
  },
  {
    metric_id: 'cost_per_lead',
    manager_key: 'leads',
    name: 'Cost per lead',
    definition: 'Ad spend divided by ad platform leads.',
    unit: 'currency',
    positive_direction: 'down',
    target: 120,
    thresholds: { watch: 160, red: 220 },
    driver_metric_ids: ['ad_spend', 'ad_leads'],
    compute_spec: { context_path: 'cpl' },
  },
  {
    metric_id: 'quality_leads',
    manager_key: 'leads',
    name: 'Qualified leads',
    definition: 'Leads meeting revenue/sobriety qualification logic.',
    unit: 'count',
    positive_direction: 'up',
    target: 35,
    thresholds: { watch: 22, red: 14 },
    driver_metric_ids: ['lead_quality_rate'],
    compute_spec: { context_path: 'quality_leads' },
  },
  {
    metric_id: 'lead_quality_rate',
    manager_key: 'leads',
    name: 'Lead quality rate',
    definition: 'Qualified leads as a share of total leads.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.28,
    thresholds: { watch: 0.22, red: 0.16 },
    driver_metric_ids: ['quality_leads', 'leads_total'],
    compute_spec: { context_path: 'quality_rate' },
  },
  {
    metric_id: 'great_leads',
    manager_key: 'leads',
    name: 'Great leads',
    definition: 'High-value leads meeting the strongest quality threshold.',
    unit: 'count',
    positive_direction: 'up',
    target: 12,
    thresholds: { watch: 8, red: 4 },
    driver_metric_ids: ['lead_quality_rate'],
    compute_spec: { context_path: 'great_leads' },
  },
  {
    metric_id: 'cost_per_quality_lead',
    manager_key: 'leads',
    name: 'Cost per qualified lead',
    definition: 'Ad spend divided by qualified leads.',
    unit: 'currency',
    positive_direction: 'down',
    target: 450,
    thresholds: { watch: 650, red: 900 },
    driver_metric_ids: ['ad_spend', 'quality_leads'],
    compute_spec: { context_path: 'cpql' },
  },
  {
    metric_id: 'luma_to_hubspot_rate',
    manager_key: 'leads',
    name: 'Registration match rate',
    definition: 'Share of Luma registrations matched back to HubSpot contacts.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.8,
    thresholds: { watch: 0.65, red: 0.5 },
    driver_metric_ids: ['luma_registrations'],
    compute_spec: { context_path: 'luma_to_hubspot_rate' },
  },
];

const ATTENDANCE_METRICS = [
  {
    metric_id: 'attendance_sessions',
    manager_key: 'attendance',
    name: 'Group sessions',
    definition: 'Distinct qualifying group sessions held during the period.',
    unit: 'count',
    positive_direction: 'up',
    target: 8,
    thresholds: { watch: 6, red: 4 },
    driver_metric_ids: ['attendance_unique_attendees'],
    compute_spec: { context_path: 'sessions_count' },
  },
  {
    metric_id: 'attendance_unique_attendees',
    manager_key: 'attendance',
    name: 'Unique attendees',
    definition: 'Unique participants attending at least one session.',
    unit: 'count',
    positive_direction: 'up',
    target: 120,
    thresholds: { watch: 90, red: 60 },
    driver_metric_ids: ['attendance_repeat_rate'],
    compute_spec: { context_path: 'unique_attendees' },
  },
  {
    metric_id: 'attendance_avg_per_session',
    manager_key: 'attendance',
    name: 'Avg attendees/session',
    definition: 'Average participant count per session.',
    unit: 'ratio',
    positive_direction: 'up',
    target: 20,
    thresholds: { watch: 15, red: 10 },
    driver_metric_ids: ['attendance_sessions', 'attendance_unique_attendees'],
    compute_spec: { context_path: 'avg_attendance_per_session' },
  },
  {
    metric_id: 'attendance_repeat_rate',
    manager_key: 'attendance',
    name: 'Repeat attendee rate',
    definition: 'Share of attendees joining multiple sessions during the period.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.4,
    thresholds: { watch: 0.3, red: 0.2 },
    driver_metric_ids: ['attendance_unique_attendees'],
    compute_spec: { context_path: 'repeat_attendee_rate' },
  },
  {
    metric_id: 'attendance_first_time',
    manager_key: 'attendance',
    name: 'First-time attendees',
    definition: 'Attendees whose first recorded attendance is in the selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 35,
    thresholds: { watch: 24, red: 14 },
    driver_metric_ids: ['attendance_unique_attendees'],
    compute_spec: { context_path: 'first_time_attendees' },
  },
  {
    metric_id: 'attendance_registrations',
    manager_key: 'attendance',
    name: 'Registrations',
    definition: 'Approved event registrations in the selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 160,
    thresholds: { watch: 120, red: 80 },
    driver_metric_ids: ['attendance_show_rate'],
    compute_spec: { context_path: 'registrations_count' },
  },
  {
    metric_id: 'attendance_show_rate',
    manager_key: 'attendance',
    name: 'Show-up rate',
    definition: 'Share of registrations that showed up to sessions.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.62,
    thresholds: { watch: 0.5, red: 0.4 },
    driver_metric_ids: ['attendance_registrations'],
    compute_spec: { context_path: 'show_up_rate' },
  },
  {
    metric_id: 'attendance_high_engagement',
    manager_key: 'attendance',
    name: 'High-engagement attendees',
    definition: 'Attendees with 3+ sessions in the selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 25,
    thresholds: { watch: 16, red: 8 },
    driver_metric_ids: ['attendance_repeat_rate'],
    compute_spec: { context_path: 'high_engagement_attendees' },
  },
  {
    metric_id: 'attendance_inactive_risk',
    manager_key: 'attendance',
    name: 'Inactive risk cohort',
    definition: 'Previously active attendees absent in this period.',
    unit: 'count',
    positive_direction: 'down',
    target: 20,
    thresholds: { watch: 28, red: 40 },
    driver_metric_ids: ['attendance_followup_volume'],
    compute_spec: { context_path: 'inactive_attendee_risk' },
  },
];

const EMAIL_METRICS = [
  {
    metric_id: 'email_campaigns_sent',
    manager_key: 'email',
    name: 'Campaigns sent',
    definition: 'Total qualifying campaigns sent in period.',
    unit: 'count',
    positive_direction: 'up',
    target: 8,
    thresholds: { watch: 6, red: 4 },
    driver_metric_ids: ['email_delivered'],
    compute_spec: { context_path: 'campaigns_sent' },
  },
  {
    metric_id: 'email_delivered',
    manager_key: 'email',
    name: 'Emails delivered',
    definition: 'Total delivered emails across campaigns.',
    unit: 'count',
    positive_direction: 'up',
    target: 40000,
    thresholds: { watch: 28000, red: 18000 },
    driver_metric_ids: ['email_human_open_rate'],
    compute_spec: { context_path: 'emails_delivered' },
  },
  {
    metric_id: 'email_human_open_rate',
    manager_key: 'email',
    name: 'Human open rate',
    definition: 'Open rate adjusted for Apple MPP auto-opens.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.42,
    thresholds: { watch: 0.34, red: 0.26 },
    driver_metric_ids: ['email_ctr', 'email_deliverability'],
    compute_spec: { context_path: 'human_open_rate' },
  },
  {
    metric_id: 'email_ctr',
    manager_key: 'email',
    name: 'CTR',
    definition: 'Unique clicks divided by delivered emails.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.03,
    thresholds: { watch: 0.022, red: 0.015 },
    driver_metric_ids: ['email_ctor'],
    compute_spec: { context_path: 'ctr' },
  },
  {
    metric_id: 'email_ctor',
    manager_key: 'email',
    name: 'CTOR',
    definition: 'Unique clicks divided by unique opens.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.12,
    thresholds: { watch: 0.09, red: 0.06 },
    driver_metric_ids: ['email_ctr'],
    compute_spec: { context_path: 'ctor' },
  },
  {
    metric_id: 'email_unsubscribe_rate',
    manager_key: 'email',
    name: 'Unsubscribe rate',
    definition: 'Unsubscribes divided by delivered emails.',
    unit: 'percent',
    positive_direction: 'down',
    target: 0.003,
    thresholds: { watch: 0.005, red: 0.008 },
    driver_metric_ids: ['email_list_health'],
    compute_spec: { context_path: 'unsubscribe_rate' },
  },
  {
    metric_id: 'email_bounce_rate',
    manager_key: 'email',
    name: 'Bounce rate',
    definition: 'Bounces divided by emails sent.',
    unit: 'percent',
    positive_direction: 'down',
    target: 0.01,
    thresholds: { watch: 0.02, red: 0.03 },
    driver_metric_ids: ['email_list_health'],
    compute_spec: { context_path: 'bounce_rate' },
  },
  {
    metric_id: 'email_clicks_total',
    manager_key: 'email',
    name: 'Unique clicks',
    definition: 'Total unique clicks across campaigns.',
    unit: 'count',
    positive_direction: 'up',
    target: 900,
    thresholds: { watch: 600, red: 350 },
    driver_metric_ids: ['email_ctr'],
    compute_spec: { context_path: 'unique_clicks' },
  },
];

const SEO_METRICS = [
  {
    metric_id: 'seo_ga_sessions',
    manager_key: 'seo',
    name: 'GA sessions',
    definition: 'Google Analytics sessions in selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 9000,
    thresholds: { watch: 7000, red: 5000 },
    driver_metric_ids: ['seo_engagement_rate'],
    compute_spec: { context_path: 'ga_sessions' },
  },
  {
    metric_id: 'seo_ga_users',
    manager_key: 'seo',
    name: 'GA users',
    definition: 'Unique users from Google Analytics in selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 7000,
    thresholds: { watch: 5500, red: 3800 },
    driver_metric_ids: ['seo_ga_sessions'],
    compute_spec: { context_path: 'ga_users' },
  },
  {
    metric_id: 'seo_engagement_rate',
    manager_key: 'seo',
    name: 'Engagement rate',
    definition: 'GA engaged sessions divided by sessions.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.58,
    thresholds: { watch: 0.48, red: 0.4 },
    driver_metric_ids: ['seo_ga_sessions'],
    compute_spec: { context_path: 'engagement_rate' },
  },
  {
    metric_id: 'seo_organic_sessions',
    manager_key: 'seo',
    name: 'Organic sessions',
    definition: 'GA sessions attributed to organic channel.',
    unit: 'count',
    positive_direction: 'up',
    target: 4200,
    thresholds: { watch: 3200, red: 2200 },
    driver_metric_ids: ['seo_organic_share'],
    compute_spec: { context_path: 'organic_sessions' },
  },
  {
    metric_id: 'seo_organic_share',
    manager_key: 'seo',
    name: 'Organic share',
    definition: 'Organic sessions share of all GA sessions.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.48,
    thresholds: { watch: 0.38, red: 0.28 },
    driver_metric_ids: ['seo_ga_sessions', 'seo_organic_sessions'],
    compute_spec: { context_path: 'organic_share' },
  },
  {
    metric_id: 'seo_gsc_clicks',
    manager_key: 'seo',
    name: 'GSC clicks',
    definition: 'Google Search Console clicks in selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 3800,
    thresholds: { watch: 2800, red: 1800 },
    driver_metric_ids: ['seo_gsc_ctr'],
    compute_spec: { context_path: 'gsc_clicks' },
  },
  {
    metric_id: 'seo_gsc_impressions',
    manager_key: 'seo',
    name: 'GSC impressions',
    definition: 'Google Search Console impressions in selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 240000,
    thresholds: { watch: 180000, red: 120000 },
    driver_metric_ids: ['seo_gsc_clicks'],
    compute_spec: { context_path: 'gsc_impressions' },
  },
  {
    metric_id: 'seo_gsc_ctr',
    manager_key: 'seo',
    name: 'GSC CTR',
    definition: 'Search Console clicks divided by impressions.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.02,
    thresholds: { watch: 0.015, red: 0.01 },
    driver_metric_ids: ['seo_gsc_clicks', 'seo_gsc_impressions'],
    compute_spec: { context_path: 'gsc_ctr' },
  },
  {
    metric_id: 'seo_avg_position',
    manager_key: 'seo',
    name: 'Avg search position',
    definition: 'Average ranking position from Search Console (lower is better).',
    unit: 'ratio',
    positive_direction: 'down',
    target: 18,
    thresholds: { watch: 24, red: 30 },
    driver_metric_ids: ['seo_gsc_ctr'],
    compute_spec: { context_path: 'avg_position' },
  },
];

const DONATIONS_METRICS = [
  {
    metric_id: 'donations_total_amount',
    manager_key: 'donations',
    name: 'Donation amount',
    definition: 'Total donation amount in selected period.',
    unit: 'currency',
    positive_direction: 'up',
    target: 30000,
    thresholds: { watch: 20000, red: 12000 },
    driver_metric_ids: ['donations_transaction_count'],
    compute_spec: { context_path: 'total_amount' },
  },
  {
    metric_id: 'donations_transaction_count',
    manager_key: 'donations',
    name: 'Donation transactions',
    definition: 'Total number of donation transactions in selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 120,
    thresholds: { watch: 85, red: 55 },
    driver_metric_ids: ['donations_unique_donors'],
    compute_spec: { context_path: 'transactions_count' },
  },
  {
    metric_id: 'donations_unique_donors',
    manager_key: 'donations',
    name: 'Unique donors',
    definition: 'Distinct donors contributing during selected period.',
    unit: 'count',
    positive_direction: 'up',
    target: 90,
    thresholds: { watch: 65, red: 40 },
    driver_metric_ids: ['donations_average_gift'],
    compute_spec: { context_path: 'unique_donors' },
  },
  {
    metric_id: 'donations_average_gift',
    manager_key: 'donations',
    name: 'Average gift',
    definition: 'Average amount per donation transaction.',
    unit: 'currency',
    positive_direction: 'up',
    target: 260,
    thresholds: { watch: 200, red: 140 },
    driver_metric_ids: ['donations_total_amount', 'donations_transaction_count'],
    compute_spec: { context_path: 'average_gift' },
  },
  {
    metric_id: 'donations_recurring_txn_share',
    manager_key: 'donations',
    name: 'Recurring txn share',
    definition: 'Share of transactions marked recurring.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.3,
    thresholds: { watch: 0.22, red: 0.14 },
    driver_metric_ids: ['donations_recurring_amount_share'],
    compute_spec: { context_path: 'recurring_txn_share' },
  },
  {
    metric_id: 'donations_recurring_amount_share',
    manager_key: 'donations',
    name: 'Recurring amount share',
    definition: 'Share of total amount coming from recurring donations.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.38,
    thresholds: { watch: 0.28, red: 0.18 },
    driver_metric_ids: ['donations_total_amount'],
    compute_spec: { context_path: 'recurring_amount_share' },
  },
  {
    metric_id: 'donations_top_donor_concentration',
    manager_key: 'donations',
    name: 'Top donor concentration',
    definition: 'Share of total amount contributed by top donor in period.',
    unit: 'percent',
    positive_direction: 'down',
    target: 0.12,
    thresholds: { watch: 0.18, red: 0.25 },
    driver_metric_ids: ['donations_unique_donors'],
    compute_spec: { context_path: 'top_donor_concentration' },
  },
  {
    metric_id: 'donations_campaign_coverage',
    manager_key: 'donations',
    name: 'Campaign attribution coverage',
    definition: 'Share of donations with campaign attribution filled.',
    unit: 'percent',
    positive_direction: 'up',
    target: 0.9,
    thresholds: { watch: 0.75, red: 0.6 },
    driver_metric_ids: ['donations_data_freshness'],
    compute_spec: { context_path: 'campaign_attribution_coverage' },
  },
  {
    metric_id: 'donations_active_supporters',
    manager_key: 'donations',
    name: 'Active supporters',
    definition: 'Supporter profile count available for stewardship workflows.',
    unit: 'count',
    positive_direction: 'up',
    target: 180,
    thresholds: { watch: 120, red: 70 },
    driver_metric_ids: ['donations_unique_donors'],
    compute_spec: { context_path: 'active_supporters' },
  },
];

const OPERATIONS_METRICS = [
  {
    metric_id: 'ops_managers_reporting',
    manager_key: 'operations',
    name: 'Managers reporting',
    definition: 'Count of managers with a fresh snapshot in this period.',
    unit: 'count',
    positive_direction: 'up',
    target: 5,
    thresholds: { watch: 4, red: 3 },
    driver_metric_ids: ['ops_data_freshness_hours'],
    compute_spec: { context_path: 'managers_reporting' },
  },
  {
    metric_id: 'ops_red_metrics',
    manager_key: 'operations',
    name: 'Red metrics',
    definition: 'Total red-status KPIs across manager snapshots.',
    unit: 'count',
    positive_direction: 'down',
    target: 3,
    thresholds: { watch: 6, red: 10 },
    driver_metric_ids: ['ops_watch_metrics'],
    compute_spec: { context_path: 'red_metrics_count' },
  },
  {
    metric_id: 'ops_watch_metrics',
    manager_key: 'operations',
    name: 'Watch metrics',
    definition: 'Total watch-status KPIs across manager snapshots.',
    unit: 'count',
    positive_direction: 'down',
    target: 8,
    thresholds: { watch: 14, red: 20 },
    driver_metric_ids: ['ops_red_metrics'],
    compute_spec: { context_path: 'watch_metrics_count' },
  },
  {
    metric_id: 'ops_green_metrics',
    manager_key: 'operations',
    name: 'Green metrics',
    definition: 'Total green-status KPIs across manager snapshots.',
    unit: 'count',
    positive_direction: 'up',
    target: 28,
    thresholds: { watch: 20, red: 14 },
    driver_metric_ids: ['ops_red_metrics'],
    compute_spec: { context_path: 'green_metrics_count' },
  },
  {
    metric_id: 'ops_data_freshness_hours',
    manager_key: 'operations',
    name: 'Data freshness (hours)',
    definition: 'Oldest source freshness age among manager snapshots.',
    unit: 'ratio',
    positive_direction: 'down',
    target: 12,
    thresholds: { watch: 24, red: 36 },
    driver_metric_ids: ['ops_managers_reporting'],
    compute_spec: { context_path: 'data_freshness_hours' },
  },
  {
    metric_id: 'ops_action_runs_7d',
    manager_key: 'operations',
    name: 'Action runs (7d)',
    definition: 'Autonomous action runs completed in the last 7 days.',
    unit: 'count',
    positive_direction: 'up',
    target: 18,
    thresholds: { watch: 10, red: 5 },
    driver_metric_ids: ['ops_improvement_velocity'],
    compute_spec: { context_path: 'action_runs_7d' },
  },
  {
    metric_id: 'ops_notion_tasks_7d',
    manager_key: 'operations',
    name: 'Human todos added (7d)',
    definition: 'Human todo items sent to Notion in the last 7 days.',
    unit: 'count',
    positive_direction: 'up',
    target: 15,
    thresholds: { watch: 8, red: 4 },
    driver_metric_ids: ['ops_improvement_velocity'],
    compute_spec: { context_path: 'notion_tasks_7d' },
  },
  {
    metric_id: 'ops_improvement_velocity',
    manager_key: 'operations',
    name: 'Improvement velocity',
    definition: 'Reduction in red metrics versus the previous comparable snapshot.',
    unit: 'count',
    positive_direction: 'up',
    target: 2,
    thresholds: { watch: 0, red: -2 },
    driver_metric_ids: ['ops_red_metrics'],
    compute_spec: { context_path: 'improvement_velocity' },
  },
];

export const METRIC_REGISTRY = {
  leads: LEADS_METRICS,
  attendance: ATTENDANCE_METRICS,
  email: EMAIL_METRICS,
  seo: SEO_METRICS,
  donations: DONATIONS_METRICS,
  operations: OPERATIONS_METRICS,
};

export function getMetricsForManager(managerKey) {
  return [...(METRIC_REGISTRY[managerKey] || [])];
}
