-- Donations module: Zeffy ingestion table + manual entries + unified view

CREATE TABLE IF NOT EXISTS public.raw_zeffy_donations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_event_id text NOT NULL,
  zeffy_donation_id text,
  zeffy_payment_id text,
  donor_name text,
  donor_email text,
  amount numeric(12,2) NOT NULL,
  currency text NOT NULL DEFAULT 'USD',
  fee_amount numeric(12,2),
  tip_amount numeric(12,2),
  net_amount numeric(12,2),
  donated_at timestamptz NOT NULL,
  source_created_at timestamptz,
  status text,
  is_recurring boolean NOT NULL DEFAULT false,
  campaign_name text,
  form_name text,
  payment_method text,
  donor_address jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'raw_zeffy_donations_source_event_id_key'
      AND conrelid = 'public.raw_zeffy_donations'::regclass
  ) THEN
    ALTER TABLE public.raw_zeffy_donations
      ADD CONSTRAINT raw_zeffy_donations_source_event_id_key UNIQUE (source_event_id);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_raw_zeffy_donations_donated_at
  ON public.raw_zeffy_donations (donated_at DESC);
CREATE INDEX IF NOT EXISTS idx_raw_zeffy_donations_donor_email
  ON public.raw_zeffy_donations (lower(donor_email));
CREATE TABLE IF NOT EXISTS public.manual_donation_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  donor_name text NOT NULL,
  donor_email text,
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  currency text NOT NULL DEFAULT 'USD',
  donated_at timestamptz NOT NULL DEFAULT now(),
  campaign_name text,
  designation text,
  note text,
  is_recurring boolean NOT NULL DEFAULT false,
  source_label text NOT NULL DEFAULT 'Manual Entry',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_manual_donation_entries_donated_at
  ON public.manual_donation_entries (donated_at DESC);
CREATE INDEX IF NOT EXISTS idx_manual_donation_entries_donor_email
  ON public.manual_donation_entries (lower(donor_email));
CREATE OR REPLACE VIEW public.donation_transactions_unified AS
SELECT
  'zeffy'::text AS source_system,
  z.id::text AS row_id,
  z.source_event_id,
  z.donor_name,
  z.donor_email,
  z.amount,
  z.currency,
  z.fee_amount,
  z.tip_amount,
  z.net_amount,
  z.donated_at,
  z.status,
  z.is_recurring,
  COALESCE(z.campaign_name, z.form_name) AS campaign_name,
  NULL::text AS designation,
  z.payment_method,
  NULL::text AS note,
  z.ingested_at AS created_at,
  z.updated_at,
  z.payload
FROM public.raw_zeffy_donations z
UNION ALL
SELECT
  'manual'::text AS source_system,
  m.id::text AS row_id,
  NULL::text AS source_event_id,
  m.donor_name,
  m.donor_email,
  m.amount,
  m.currency,
  NULL::numeric AS fee_amount,
  NULL::numeric AS tip_amount,
  NULL::numeric AS net_amount,
  m.donated_at,
  'posted'::text AS status,
  m.is_recurring,
  m.campaign_name,
  m.designation,
  NULL::text AS payment_method,
  m.note,
  m.created_at,
  m.updated_at,
  m.metadata AS payload
FROM public.manual_donation_entries m;
