-- Expand donations schema for Zeffy export backfills and richer KPI visualizations.

ALTER TABLE public.raw_zeffy_donations
  ADD COLUMN IF NOT EXISTS donor_first_name text,
  ADD COLUMN IF NOT EXISTS donor_last_name text,
  ADD COLUMN IF NOT EXISTS donor_company_name text,
  ADD COLUMN IF NOT EXISTS donor_language text,
  ADD COLUMN IF NOT EXISTS donor_city text,
  ADD COLUMN IF NOT EXISTS donor_region text,
  ADD COLUMN IF NOT EXISTS donor_postal_code text,
  ADD COLUMN IF NOT EXISTS donor_country text,
  ADD COLUMN IF NOT EXISTS eligible_amount numeric(12,2),
  ADD COLUMN IF NOT EXISTS receipt_url text,
  ADD COLUMN IF NOT EXISTS source_file text,
  ADD COLUMN IF NOT EXISTS is_historical_backfill boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_raw_zeffy_donations_payment_method
  ON public.raw_zeffy_donations (payment_method);

CREATE INDEX IF NOT EXISTS idx_raw_zeffy_donations_campaign_name
  ON public.raw_zeffy_donations (campaign_name);

CREATE INDEX IF NOT EXISTS idx_raw_zeffy_donations_source_file
  ON public.raw_zeffy_donations (source_file);

CREATE TABLE IF NOT EXISTS public.raw_zeffy_supporter_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_email text NOT NULL,
  donor_name text,
  donor_first_name text,
  donor_last_name text,
  donor_language text,
  donor_company_name text,
  donor_address text,
  donor_city text,
  donor_region text,
  donor_postal_code text,
  donor_country text,
  commitment_amount numeric(12,2),
  first_payment_at timestamptz,
  last_payment_at timestamptz,
  manual_lists text[] NOT NULL DEFAULT '{}',
  source_file text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  imported_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT raw_zeffy_supporter_profiles_donor_email_key UNIQUE (donor_email)
);

CREATE INDEX IF NOT EXISTS idx_raw_zeffy_supporter_profiles_email
  ON public.raw_zeffy_supporter_profiles (lower(donor_email));

CREATE OR REPLACE VIEW public.donation_transactions_unified AS
SELECT
  'zeffy'::text AS source_system,
  z.id::text AS row_id,
  z.source_event_id,
  z.donor_name,
  z.donor_email,
  z.amount,
  z.currency,
  z.fee_amount,
  z.tip_amount,
  z.net_amount,
  z.eligible_amount,
  z.donated_at,
  z.status,
  z.is_recurring,
  COALESCE(z.campaign_name, z.form_name) AS campaign_name,
  NULL::text AS designation,
  z.payment_method,
  z.receipt_url,
  z.donor_city,
  z.donor_region,
  z.donor_country,
  z.source_file,
  NULL::text AS note,
  z.ingested_at AS created_at,
  z.updated_at,
  z.payload
FROM public.raw_zeffy_donations z
UNION ALL
SELECT
  'manual'::text AS source_system,
  m.id::text AS row_id,
  NULL::text AS source_event_id,
  m.donor_name,
  m.donor_email,
  m.amount,
  m.currency,
  NULL::numeric AS fee_amount,
  NULL::numeric AS tip_amount,
  NULL::numeric AS net_amount,
  NULL::numeric AS eligible_amount,
  m.donated_at,
  'posted'::text AS status,
  m.is_recurring,
  m.campaign_name,
  m.designation,
  NULL::text AS payment_method,
  NULL::text AS receipt_url,
  NULL::text AS donor_city,
  NULL::text AS donor_region,
  NULL::text AS donor_country,
  NULL::text AS source_file,
  m.note,
  m.created_at,
  m.updated_at,
  m.metadata AS payload
FROM public.manual_donation_entries m;
